// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type FileUploadMultipartRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadMultipartResponse struct {
	Identity string `json:"identity"`
}

type FileUploadRequest struct {
	Hash string `json:"hash,optional"`
	Name string `json:"name,optional"`
	Ext  string `json:"ext,optional"`
	Size int64  `json:"size,optional"`
	Path string `json:"path,optional"`
}

type FileUploadResponse struct {
	Identity string `json:"identity"`
	Ext      string `json:"ext"`
	Name     string `json:"name"`
}

type FolderPathItem struct {
	Id       int64  `json:"id"`
	Identity string `json:"identity"`
	Name     string `json:"name"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type MailCodeRequest struct {
	Email string `json:"email"`
}

type MailCodeResponse struct {
	Code string `json:"code"`
}

type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

type RefreshTokenResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
}

type ShareBasicCreateRequest struct {
	UserRepositoryIdentity string `json:"user_repository_identity"`
	ExpiredTime            int    `json:"expired_time"`
}

type ShareBasicCreateResponse struct {
	Identity string `json:"identity"`
}

type ShareBasicDetailRequest struct {
	Identity string `json:"identity"`
}

type ShareBasicDetailResponse struct {
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
}

type ShareFileDetailRequest struct {
	Identity string `path:"identity"`
}

type ShareFileDetailResponse struct {
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Size               int64  `json:"size"`
	Path               string `json:"path"`
}

type ShareFileSaveRequest struct {
	RepositoryIdentity string `json:"repository_identity"`
	ParentId           int64  `json:"parent_id"`
}

type ShareFileSaveResponse struct {
	Identity string `json:"identity"`
}

type UserDetailRequest struct {
	Identity string `json:"identity, optional"`
}


type UserDetailResponse struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type UserFile struct {
	Id                 int64  `json:"id"`
	Identity           string `json:"identity"`
	RepositoryIdentity string `json:"repository_identity"`
	Name               string `json:"name"`
	Ext                string `json:"ext"`
	Path               string `json:"path"`
	Size               int64  `json:"size"`
	IsDir              int    `json:"is_dir"` //是否是文件夹 1 是 0 不是
}

type UserFileDeleteRequest struct {
	Identity string `json:"identity"`
}

type UserFileDeleteResponse struct {
}

type UserFileListRequest struct {
	Id       int64  `json:"id,optional"`       // 兼容旧逻辑，按父级 id 查询
	Identity string `form:"identity,optional"` // 目录唯一凭证，优先使用这个查询目录内容
	Page     int    `json:"page,optional"`     // 第几页
	Size     int    `json:"size,optional"`     // 每页文件数量
}

type UserFileListResponse struct {
	List  []*UserFile `json:"list"`
	Count int64       `json:"count"` //list总数量
}

type UserFileMoveRequest struct {
	ParentIdentity string `json:"parent_identity"`
	Identity       string `json:"identity"`
}

type UserFileMoveResponse struct {
}

type UserFileNameUpdateRequest struct {
	Name     string `json:"name"`
	Identity string `json:"identity"` //用户文件存储的唯一凭证
}

type UserFileNameUpdateResponse struct {
}

type UserFolderChildrenRequest struct {
	Id int64 `path:"id"`
}

type UserFolderChildrenResponse struct {
	List []*UserFolderNode `json:"list"`
}

type UserFolderCreateRequest struct {
	Name     string `json:"name"`
	ParentId int64  `json:"parentId"`
}

type UserFolderCreateResponse struct {
	Identity string `json:"identity"`
}

type UserFolderNode struct {
	Id          int64  `json:"id"`
	Identity    string `json:"identity"`
	ParentId    int64  `json:"parent_id"`
	Name        string `json:"name"`
	HasChildren int    `json:"has_children"`
}

type UserFolderPathRequest struct {
	Identity string `path:"identity"` //用户文件唯一凭证
}

type UserFolderPathResponse struct {
	List []*FolderPathItem `json:"list"`
}

type UserRegisterRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
	Email    string `json:"email"`
	Code     string `json:"code"`
}

type UserRegisterResponse struct {
}

type UserRepositySaveRequest struct {
	ParentId         int64  `json:"parentId"`
	ReposityIdentity string `json:"repositoryIdentity"`
	Ext              string `json:"ext"`
	Name             string `json:"name"`
}

type UserRepositySaveResponse struct {
}
